carbon_project_rater:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      port: 5432
      user: postgres
      password: password
      dbname: carbon_project_rater
      schema: public
      threads: 4