carbon_project_rater:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: carbon_project_rater
      schema: dbt_carbon_project_rater